pipeline:
  name: Build CacheTestRepo
  identifier: Build_avijeetsm_CacheTestRepo_1732201907122
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Plugin
                  name: Plugin_1
                  identifier: Plugin_1
                  spec:
                    connectorRef: account.harnessImage
                    image: avijeetsm/drone-cache
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    shell: Powershell
                    command: |-
                      cd csharp
                      dotnet restore
                      dotnet build
                      dotnet nuget locals all --list
                      Get-ChildItem -Force | Sort-Object LastWriteTime | Format-Table -Property Mode, LastWriteTime, Length, Name
                      cat nuget.config
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: true
            paths: []
          buildIntelligence:
            enabled: false
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1732201874249
        repoName: avijeetsm/CacheTestRepo
        build: <+input>
